build:
  environment:
    php: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      dependencies:
        before:
          - wget https://ftp.gnu.org/gnu/wget/wget-latest.tar.gz
          - tar xf wget-latest.tar.gz
          - cd wget-*
          - ./configure
          - sudo make
          - sudo make install
      tests:
        override:
          - command: composer test -- --coverage-clover build/coverage.xml
            idle_timeout: 600
            coverage:
              file: build/coverage.xml
              format: clover

filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

